version: '3.8'

services:
  app:
    build: .
    expose:
      - "8000"
    env_file: 
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    command: ["granian", "--interface", "asgi", "--host", "0.0.0.0", "--port", "8000", "app.main:app"]

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      app:
        condition: service_started
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  db:
    image: postgres:latest
    env_file: 
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 15
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: